-- Create table if it doesn't exist
create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  score bigint not null
);

-- Add new columns if they don't exist
do $$ 
begin
  -- Add code column (renamed from name)
  if not exists (select 1 from information_schema.columns where table_name = 'leaderboard' and column_name = 'code') then
    alter table public.leaderboard add column code text;
  end if;
  
  -- Add email column
  if not exists (select 1 from information_schema.columns where table_name = 'leaderboard' and column_name = 'email') then
    alter table public.leaderboard add column email text;
  end if;
  
  -- Add user_id column
  if not exists (select 1 from information_schema.columns where table_name = 'leaderboard' and column_name = 'user_id') then
    alter table public.leaderboard add column user_id uuid references auth.users(id);
  end if;
  
  -- Add verified column
  if not exists (select 1 from information_schema.columns where table_name = 'leaderboard' and column_name = 'verified') then
    alter table public.leaderboard add column verified boolean default false;
  end if;
end $$;

-- Migrate data from 'name' column to 'code' if 'name' exists
do $$
begin
  if exists (select 1 from information_schema.columns where table_name = 'leaderboard' and column_name = 'name') then
    update public.leaderboard set code = name where code is null and name is not null;
    alter table public.leaderboard drop column name;
  end if;
end $$;

-- Make code not null after migration
alter table public.leaderboard alter column code set not null;

-- Update created_at to have default if it doesn't
alter table public.leaderboard alter column created_at set default now();

-- Create index for faster queries
create index if not exists idx_leaderboard_score on public.leaderboard(score desc);
create index if not exists idx_leaderboard_verified on public.leaderboard(verified);
create index if not exists idx_leaderboard_user_id on public.leaderboard(user_id);

-- Enable Row Level Security
alter table public.leaderboard enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Leaderboard entries are publicly readable" on public.leaderboard;
drop policy if exists "Users can insert their own scores" on public.leaderboard;

-- Policy: Anyone can read leaderboard entries
create policy "Leaderboard entries are publicly readable"
  on public.leaderboard for select
  using (true);

-- Policy: Authenticated users can insert their own scores
create policy "Users can insert their own scores"
  on public.leaderboard for insert
  with check (
    (auth.uid() = user_id) or (user_id is null)
  );

